const init=Array.from({length:5},()=>['','', '', 'mid', '', '', 0]);
const probs={low:35,mid:45,high:55};
const cards=document.querySelector('#cards');
init.forEach((d,i)=>{const el=document.createElement('div');el.className='card';el.innerHTML=`<label><span class="slot">${i+1}</span>キャラ<input data-k="name" value="${d[0]}"></label><label>衣装<input data-k="costume" value="${d[1]}"></label><label>周期(s)<input data-k="interval" type="number" min="0.01" step="0.01" value="${d[2]}"></label><label>確率<select data-k="prob"><option value="low">低</option><option value="mid">中</option><option value="high">高</option></select></label><label>発動時間(s)<input data-k="duration" type="number" min="0" step="0.01" value="${d[4]}"></label><label>補正(%)<input data-k="boost" type="number" min="0" step="0.01" value="${d[5]}"></label><label>短縮<select data-k="short"><option>0</option><option>4</option><option>8</option><option>12</option></select></label>`;el.querySelector('[data-k=prob]').value=d[3];el.querySelector('[data-k=short]').value=d[6];cards.append(el)});
function num(v,f=0){const x=Number(v);return Number.isFinite(x)?x:f}
function getMembers(){return [...document.querySelectorAll('.card')].map((c,i)=>{const g=k=>c.querySelector(`[data-k=${k}]`).value;return{slot:i+1,name:g('name')||`枠${i+1}`,costume:g('costume'),interval:Math.max(0,num(g('interval'),0)),prob:g('prob'),duration:Math.max(0,num(g('duration'))),boost:Math.max(0,num(g('boost'))),short:num(g('short'))}})}
// α版の短縮計算は base interval × (1 - short/100)。仕様確定時はこの1関数だけ差し替え可能。
function adjustedInterval(m){return m.interval>0?m.interval*(1-m.short/100):0}
function events(m,T){const iv=adjustedInterval(m),out=[];if(iv<=0||m.duration<=0||m.boost<=0)return out;for(let t=iv;t<=T+1e-9&&out.length<1000;t+=iv)out.push({start:t,end:Math.min(T,t+m.duration),boost:m.boost,m});return out}
function calcMax(all,T){const pts=[0,T];all.forEach(e=>{pts.push(e.start,e.end)});pts.sort((a,b)=>a-b);let total=0;for(let i=0;i<pts.length-1;i++){const a=pts[i],b=pts[i+1];if(b<=a)continue;const mid=(a+b)/2;let mx=0;for(const e of all)if(e.start<=mid&&mid<e.end)mx=Math.max(mx,e.boost);total+=mx*(b-a)}return total}

function maxSegments(all,T){const pts=[0,T];all.forEach(e=>{pts.push(e.start,e.end)});pts.sort((a,b)=>a-b);const segments=[];for(let i=0;i<pts.length-1;i++){const a=pts[i],b=pts[i+1];if(b<=a)continue;const mid=(a+b)/2;let mx=0;for(const e of all)if(e.start<=mid&&mid<e.end)mx=Math.max(mx,e.boost);if(mx>0){const prev=segments[segments.length-1];if(prev&&Math.abs(prev.end-a)<1e-9&&prev.boost===mx)prev.end=b;else segments.push({start:a,end:b,boost:mx})}}return segments}
function render(){const T=Math.max(.01,num(document.querySelector('#song').value,120)),ms=getMembers(),by=ms.map(m=>events(m,T)),all=by.flat(),max=calcMax(all,T);document.querySelector('#max').textContent=max.toFixed(2);document.querySelector('#avg').textContent=`+${(max/T).toFixed(2)}%`;document.querySelector('#count').textContent=all.length;const tl=document.querySelector('#timeline');tl.innerHTML='';

const activeRow=document.createElement('div');activeRow.className='row maxrow';activeRow.innerHTML=`<div class="name">有効スキル<br><span class="sub">全発動時</span></div><div class="track"></div>`;const activeTrack=activeRow.lastElementChild;maxSegments(all,T).forEach(seg=>{const b=document.createElement('button');b.type='button';b.className='bar';b.style.left=(seg.start/T*100)+'%';b.style.width=((seg.end-seg.start)/T*100)+'%';b.title=`${seg.start.toFixed(2)}–${seg.end.toFixed(2)}s / +${seg.boost.toFixed(2)}%`;b.addEventListener('click',()=>{document.querySelector('#detail').textContent=`有効スキル — ${seg.start.toFixed(2)}s → ${seg.end.toFixed(2)}s / 有効補正 +${seg.boost.toFixed(2)}%`});activeTrack.append(b)});tl.append(activeRow);

const axis=document.createElement('div');axis.className='axis';axis.innerHTML='<div></div><div class="axisTrack"></div>';const at=axis.lastElementChild;for(let i=0;i<=10;i++){const x=i*10,t=T*i/10,d=document.createElement('div');d.className='tick';d.style.left=x+'%';d.innerHTML=`<span>${t.toFixed(2)}</span>`;at.append(d)}tl.append(axis);

ms.forEach((m,i)=>{const row=document.createElement('div');row.className=`row slot${i+1}`;row.innerHTML=`<div class="name">${m.slot}. ${m.name}<br><span class="sub">${m.interval>0?adjustedInterval(m).toFixed(2)+'s周期':'未入力'}</span></div><div class="track"></div>`;const tr=row.lastElementChild;by[i].forEach((e,n)=>{const b=document.createElement('button');b.type='button';b.className='bar';b.style.left=(e.start/T*100)+'%';b.style.width=(Math.max(0,e.end-e.start)/T*100)+'%';b.title=`${e.start.toFixed(2)}–${e.end.toFixed(2)}s`;b.addEventListener('click',()=>{document.querySelector('#detail').textContent=`${m.name} / ${m.costume||'衣装未入力'} — 第${n+1}候補 ${e.start.toFixed(2)}s → ${e.end.toFixed(2)}s / ${m.prob==='low'?'低':m.prob==='mid'?'中':'高'} ${probs[m.prob].toFixed(2)}% / +${m.boost.toFixed(2)}% / 短縮 ${m.short.toFixed(2)}%`});tr.append(b)});tl.append(row)})}
document.addEventListener('input',e=>{if(e.target.closest('.wrap'))render()});document.addEventListener('change',e=>{if(e.target.closest('.wrap'))render()});render();
