"""Deterministic read-only projection of complete Canonical into a browser catalog.
Canonical/Source/schema are never written. --check only compares generated bytes.
"""
import argparse
import hashlib
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CANONICAL = ROOT / 'research/canonical-cards.json'
MEMBERS = ROOT / 'members.js'
OUTPUT = ROOT / 'data/runtime-cards.json'
# Identity and routing are recoverable via the Canonical JSON pointer. Game
# values/unknown fields are not normalized; absent/null/zero remain distinct.
ROUTING = {'id', 'groupId', 'descriptionLangId', 'level', 'livePassiveSkillId',
           'liveActiveSkillId', 'liveSpecialSkillId', 'livePassiveSkillEffectGroupId',
           'liveActiveSkillEffectGroupId', 'additionalLiveActiveSkillEffectGroupId',
           'liveSkillTriggerGroupId', 'additionalLiveSkillTriggerGroupId',
           'liveSkillEffectTargetId'}


def sha(data):
    return hashlib.sha256(data).hexdigest()


def values(facts, source):
    return {f['sourceField']: f['rawValue'] for f in facts if f['source'] == source}


def description(facts):
    texts = [f['rawValue'] for f in facts if f['sourceField'] == 'text' and f['source']['table'].startswith('Lang')]
    assert len(texts) <= 1, 'Multiple descriptions need explicit locale handling'
    return {'description': texts[0]} if texts else {}


def entity(data, path):
    raw = values(data['facts'], data['source'])
    return {'source': path, 'raw': {k: v for k, v in raw.items() if k not in ROUTING}, **description(data['facts'])}


def clauses(facts):
    sources = []
    for f in facts:
        if not f['source']['table'].startswith('Lang') and f['source'] not in sources:
            sources.append(f['source'])
    return [{k: v for k, v in values(facts, source).items() if k not in ROUTING} for source in sources]


def condition(parent, path):
    if 'condition' not in parent:
        return {'state': 'unobserved', 'evaluationStatus': 'unresolved'}
    original = parent['condition']
    if original is None:
        return {'state': 'explicit-null', 'value': None, 'evaluationStatus': 'unresolved', 'source': path}
    # Keep explicit source condition objects (including an explicit none marker)
    # distinct from missing evidence. Never synthesize an unconditional effect.
    if 'sourceFacts' not in original:
        return {'state': 'explicit', 'value': original, 'evaluationStatus': 'unresolved', 'source': path}
    return {'state': 'observed', 'source': path, 'clauses': clauses(original['sourceFacts']),
            **description(original['sourceFacts']),
            **{k: original[k] for k in ('resolutionClass', 'evaluationMode') if k in original},
            'evaluationStatus': 'not-evaluated'}


def project_level(level, kind, path):
    result = {'level': level['levelFact']['rawValue'], **entity(level, path)}
    if kind == 'passive':
        p = level['effect']
        target = p['target']
        result.update(effect=entity(p['effect'], path + '/effect/effect'),
                      target={'source': path + '/effect/target', 'selectors': clauses(target.get('sourceFacts', [])), **description(target.get('sourceFacts', []))},
                      condition=condition(p, path + '/effect/condition'), calculationStatus='deferred')
    elif kind == 'active':
        result.update(baseEffect=entity(level['baseEffect'], path + '/baseEffect'), conditionalOverrides=[], calculationStatus='base-only')
        for i, item in enumerate(level['conditionalOverrides']):
            base = path + f'/conditionalOverrides/{i}'
            result['conditionalOverrides'].append({'condition': condition(item, base + '/condition'), 'replacementEffect': entity(item['replacementEffect'], base + '/replacementEffect')})
        if 'evaluationScope' in level:
            result['evaluationScope'] = level['evaluationScope']
        text = result.get('description', '')
        matches = [value for label, value in [('低確率', 'low'), ('中確率', 'mid'), ('高確率', 'high')] if label in text]
        result['qualitativeProbability'] = {'status': 'candidate', 'value': matches[0], 'basis': 'localized-description'} if len(matches) == 1 else {'status': 'unresolved'}
    else:
        result.update(effects=[], durationScope='unresolved-per-effect', calculationStatus='display-only')
        for i, item in enumerate(level['effects']):
            base = path + f'/effects/{i}'
            result['effects'].append({'effect': entity(item['effect'], base + '/effect'), 'condition': condition(item, base + '/condition')})
        if 'effectCombination' in level:
            result['effectCombination'] = level['effectCombination']
    return result


def project(canonical, canonical_bytes, members_bytes):
    members = re.findall(r"id: '([^']+)',\s*name: '([^']+)'", members_bytes.decode())
    assert members, 'Cannot read the existing member master'
    cards = []
    for i, card in enumerate(canonical['cards']):
        path = f'/cards/{i}'
        names = [n['textFact']['rawValue'] for n in card['identity']['names'] if n['locale'] == 'ja-JP']
        assert len(names) == 1
        mf = card['identity']['memberFacts']
        name_id = next(f['rawValue'] for f in mf if f['source']['table'] == 'Character' and f['sourceField'] == 'nameLangId')
        name = next(f['rawValue'] for f in mf if f['source']['sourceId'] == name_id and f['sourceField'] == 'text')
        candidates = [id for id, label in members if label == name]
        mapping = {'status': 'candidate', 'id': candidates[0], 'basis': 'unique-exact-ja-name'} if len(candidates) == 1 else {'status': 'unresolved'}
        classification = {}
        for f in card['classification']:
            classification[f['sourceField']] = {'raw': f['rawValue']}
            if 'semanticCandidate' in f:
                classification[f['sourceField']]['mapping'] = f['semanticCandidate']
        progression = card['progression']
        stages = [{'stage': s['trainingCountFact']['rawValue'], 'levelCap': s['levelLimitFact']['rawValue'], 'source': path + f'/progression/trainingStages/{j}'} for j, s in enumerate(progression['trainingStages'])]
        keep = {1, *(s['levelCap'] for s in stages)}
        snapshots = []
        for j, row in enumerate(progression['levelRows']):
            raw = values(row['facts'], row['source'])
            if raw['level'] in keep:
                snapshots.append({'level': raw['level'], **entity(row, path + f'/progression/levelRows/{j}')})
        assert {s['level'] for s in snapshots} == keep, 'Missing actual level snapshot; do not fabricate'
        cards.append({'id': card['sourceCard']['sourceId'], 'source': path, 'name': names[0], 'member': {'name': name, 'mapping': mapping},
                      'classification': classification,
                      'skills': {kind: {'levels': [project_level(l, kind, path + f'/skills/{kind}/levels/{j}') for j, l in enumerate(card['skills'][kind]['levels'])]} for kind in ('passive', 'active', 'special')},
                      'progression': {'trainingStages': stages, 'statSnapshots': snapshots,
                                      'parameterInputs': {f['sourceField']: f['rawValue'] for f in progression['parameterInputFacts']},
                                      'statStatus': 'raw-inputs-only-formula-unresolved'}})
    result = {'format': 'holodori-runtime-catalog-v1',
            'dataset': {'canonicalSha256': sha(canonical_bytes), 'canonicalPath': 'research/canonical-cards.json',
                        'canonicalSchemaVersion': canonical['schemaVersion'], 'sourceDataset': canonical['sourceDataset'],
                        'sourceArtifact': canonical['conversionEvidence']['inputArtifact'],
                        'memberMaster': {'path': 'members.js', 'sha256': sha(members_bytes)},
                        'unresolved': canonical['conversionEvidence']['unresolvedItems']}, 'cards': cards}
    result['dataset']['version'] = sha(json.dumps(result, ensure_ascii=False, separators=(',', ':')).encode())
    return result


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    data = CANONICAL.read_bytes()
    result = project(json.loads(data), data, MEMBERS.read_bytes())
    ids = [c['id'] for c in result['cards']]
    assert len(ids) == len(set(ids)) == 185
    encoded = (json.dumps(result, ensure_ascii=False, separators=(',', ':')) + '\n').encode()
    if args.check:
        assert OUTPUT.read_bytes() == encoded, 'Regenerate Runtime Catalog'
    else:
        OUTPUT.parent.mkdir(exist_ok=True)
        OUTPUT.write_bytes(encoded)
    print(f'Runtime: {len(ids)} cards, {len(encoded):,} bytes; reduction {100 * (1 - len(encoded)/len(data)):.4f}%; ' + ('reproduction PASS' if args.check else 'generated'))


if __name__ == '__main__':
    main()
